global:
  scrape_interval: 5s
scrape_configs:
- job_name: app-pagamentos
  metrics_path: /actuator/prometheus
  static_configs:
    - targets: ['host.docker.internal:8082']
- job_name: app-pedidos
  metrics_path: /actuator/prometheus
  static_configs:
    - targets: ['host.docker.internal:8083']